pool:
    name: Hosted VS2019
    demands: npm

pr: none

trigger:
    branches:
        exclude:
            - '*'
    tags:
        include:
            - v*-internal

steps:
- task: TfxInstaller@3
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.9.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: replacetokens@4
  inputs:
    targetFiles: '**/signalr.ts'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    actionOnNoFiles: 'fail'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm run package-release-internal'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run package-release-internal'

- task: PublishAzureDevOpsExtension@3
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: Marketplace
    fileType: vsix
    vsixFile: 'joshuacampbell.estimate-*.vsix'
    updateTasksVersion: false
