pool:
    name: Hosted VS2017
    demands: npm

pr: none

trigger:
    branches:
        exclude:
            - '*'
    tags:
        include:
            - v*-internal

steps:
    - task: TfxInstaller@3
      displayName: "Use Node CLI for Azure DevOps"
      inputs:
        version: 'v0.9.x'

    - task: Npm@1
      displayName: "npm install"
      inputs:
          verbose: false

    - script: npm run build

    - script: npm run package-release-internal

    

    - task: PublishAzureDevOpsExtension@3
      displayName: "Publish Extension"
      inputs:
          connectTo: 'VsTeam'
          connectedServiceName: Marketplace
          fileType: vsix
          vsixFile: "joshuacampbell.estimate-*.vsix"
          updateTasksVersion: false

    
