pool:
    name: Hosted VS2017
    demands: npm

pr: none

trigger:
    branches:
        exclude:
            - '*'
    tags:
        include:
            - v*-internal

steps:
    - task: Npm@1
      displayName: "npm install"
      inputs:
          verbose: false

    - script: npm run build

    - script: npm run package-release-internal

    - task: PublishAzureDevOpsExtension@3
      displayName: "Publish Extension"
      inputs:
          connectedServiceName: Marketplace cschleiden
          fileType: vsix
          vsixFile: "cschleiden.estimate-*.vsix"
          updateTasksVersion: false

    