pool:
    name: Hosted VS2017
    demands: npm

pr: none

trigger:
    branches:
        exclude:
            - '*'
    tags:
        include:
            - v*
        exclude:
            - v*-internal

steps:
- task: TfxInstaller@3
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.9.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm run package-release-internal'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run package-release-internal'

- task: PublishAzureDevOpsExtension@3
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: Marketplace
    fileType: vsix
    vsixFile: 'joshuacampbell.estimate-*.vsix'
    updateTasksVersion: false